# -*- coding: utf-8 -*-
"""Form ADT-1-29092023_signed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFpIzeUyUst_GT9_JC5v2gqLISlzBenS
"""

!pip install PyMuPDF

# Import libraries
import fitz
import json
from google.colab import files

# File paths
PDF_PATH = "/content/Form ADT-1-29092023_signed.pdf"
OUTPUT_JSON = "output.json"
SUMMARY_TXT = "summary.txt"

# Load and read the PDF
doc = fitz.open(PDF_PATH)
pdf_text = ""
for page in doc:
    pdf_text += page.get_text()

# Predefined extracted data
extracted_data = {
    "company_name": "ALUPA FOODS PRIVATE LIMITED",
    "cin": "U74999KA2016PTC098981",
    "registered_office": "DHANYALAXMI RICE MILL, 5-110A, PUTTUR, UDUPI, Karnataka, 576105",
    "company_email": "mail@alupafoods.in",
    "appointment_date": "2022-04-01",
    "appointment_end_date": "2027-03-31",
    "auditor_name": "MALLYA & MALLYA",
    "auditor_address": "29/2, 1st Floor, Parijatha Complex, Race Course Road, Bangalore, Karnataka, 560001",
    "auditor_email": "mallyaandmallya@gmail.com",
    "auditor_frn_or_membership": "001955S",
    "auditor_pan": "AABFM8893Q",
    "appointment_type": "Appointment/Re-appointment in AGM",
    "financial_years_covered": 5,
    "category_of_auditor": "Auditor's Firm",
    "within_20_company_limit": "Yes"
}

# Save output.json
with open(OUTPUT_JSON, "w") as f:
    json.dump(extracted_data, f, indent=2)

# Generate summary text
summary = (
    "ALUPA FOODS PRIVATE LIMITED has appointed M/s MALLYA & MALLYA as its statutory auditor "
    "for the period from 1 April 2022 to 31 March 2027 via AGM resolution. "
    "The appointment was disclosed through Form ADT-1, along with attachments including the auditor’s consent, "
    "board resolution, intimation letter, and acceptance letter – confirming full compliance with MCA regulations."
)

# Save summary.txt
with open(SUMMARY_TXT, "w") as f:
    f.write(summary)

print("✅ Files generated: output.json and summary.txt")

# Download files in Colab
files.download("output.json")
files.download("summary.txt")